thebrick/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('thebrickApp.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

thebrickApp/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',views.index, name='index'),
    path('lanzamientos/',views.lanzamiento, name='lanzamiento'),
    path('hombre/',views.hombre, name='hombre'),
    path('mujer/',views.mujer, name='mujer'),
    path('oferta/',views.oferta, name='oferta'),
    path('formulario/',views.formulario,name='formulario'),
    path('registro/',views.mostrar_registro,name='mostrar_registro'), #Registro
    path('login/',views.mostrar_entrar, name = 'mostrar_entrar'), #Login
    path('accounts/',include('django.contrib.auth.urls')),
    path('agregar_stock/',views.agregar_stock, name="agregar_stock"),
    path('listar/',views.listar,name="listar"),
    path('modificar/<id>/',views.modificar,name="modificar"),
    path('eliminar/<id>/',views.eliminar, name = "eliminar"),
    path('carrito/',views.carrito,name="carrito"),
    path('agregar/<id>/', views.agregar_producto, name="Add"),#Carrito
    path('eliminar/<id>/', views.eliminar_producto, name="Del"),
    path('restar/<id>/', views.restar_producto, name="Sub"),
    path('limpiar/', views.limpiar_carrito, name="CLS"),
    path('total_carrito',views.total_carrito,name="total_carrito"),
]

if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

thebrickApp/models.py
from django.db import models

class Producto(models.Model):
    nombre = models.CharField(max_length=60)
    precio = models.IntegerField()
    descripcion = models.TextField()
    marca = models.CharField(max_length=60)
    imagen = models.ImageField(upload_to="productos",null=True)
    talla = models.IntegerField()
    genero = models.CharField(max_length=60)

    def __str__(self):
        return self.nombre
    

thebrickApp/forms.py
from django.forms import (Form,
EmailField, 
EmailInput, 
CharField, 
PasswordInput,
BooleanField,
CheckboxInput,
TextInput
)
from django.contrib.auth.forms import BaseUserCreationForm
from django import forms
from django.contrib.auth.models import User
from .models import Producto


   
class FormularioRegistro(BaseUserCreationForm):
    def __init__(self, *args,**kargs):
        super().__init__(*args,**kargs)
        self.fields['password1'].widget.attrs = { 'class': 'form-control' }
        self.fields['password2'].widget.attrs = { 'class': 'form-control' }
        
    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name', 
            'email',
            'password1',
            'password2'
        ]
        widgets = {
            'username' : TextInput( attrs = { 'class':'form-control' }),
            'first_name' : TextInput( attrs = { 'class':'form-control' }),
            'last_name' : TextInput( attrs = { 'class':'form-control' }),
            'email' : EmailInput( attrs = { 'class':'form-control' }),
            'password1' : PasswordInput( attrs = { 'class':'form-control'}),
            'password2' : PasswordInput( attrs = { 'class':'form-control'})
        }


class FormularioLogin(Form):
    correo_usuario = EmailField(
        required=True,
        label = 'Ingrese su correo',
        widget = EmailInput(
            attrs = {
                'class':'form-control',
                'placeholder': 'name@example.com'
            }
        )
    )
    contrasenia_usuario = CharField(
        required=True,
        min_length=4,
        max_length=16,
        label='Ingrese su contraseña',
        widget=PasswordInput(
            attrs = {
                'class': 'form-control',
                'placeholder': 'Password'
            }
        )
    )
    recuerdame = BooleanField(
        required=False,
        label = "Recuerdame",
        widget = CheckboxInput()
    )
    
class ProductoForm(forms.ModelForm):

    class Meta:
        model = Producto 
        fields = '__all__'

thebrickApp/views.py
from collections import UserDict, UserList
from .forms import ProductoForm, Producto
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from thebrickApp.Carrito import Carrito
from .forms import FormularioLogin, FormularioRegistro
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login



#Registro
def mostrar_registro(request):
    if request.method == 'GET':
        contexto = {
            'formulario': FormularioRegistro()
        }
        return render(request,'registration/registro.html', contexto)
    if request.method == 'POST':
        datos_formulario = FormularioRegistro(data=request.POST)
        print(datos_formulario.data)
        es_valido = datos_formulario.is_valid()
        print(es_valido)
        if es_valido: # Preguntamos por el True
            datos_formulario.save()
            username = datos_formulario.cleaned_data['username']
            (request, f'gracias por registrarte { username }')
            return redirect('login')
        contexto = {
            'formulario': datos_formulario
        }
    return render(request,'registration/registro.html',contexto)

#Login

def mostrar_entrar(request):
    if request.method == 'GET':
        contexto = {
            'formulario':FormularioLogin(),
            'titulo':'Bienvenido',
            'formulario_original': AuthenticationForm()
        }
        return render(request, 'registration/login.html',contexto)
    elif request.method == 'POST':
        datos_usuario = AuthenticationForm(data=request.POST)
        print(datos_usuario.data)
        es_valido = datos_usuario.is_valid()
        print(datos_usuario.errors)
        if es_valido:
            username = datos_usuario.cleaned_data['username']
            password = datos_usuario.cleaned_data['password']
            print(username,password)
            usuario = authenticate(username=username,password=password)
            if usuario is not None:
                login(request,usuario)
                return redirect('index')
            else:
                # Mandar al lobby
                return redirect('index')
        contexto = {
            'titulo':'Bienvenido',
            'formulario_original': datos_usuario,
            'formulario':FormularioLogin()
        }


def index(request):
    return render(request,'index.html')

def lanzamiento(request):
    return render(request,'lanzamiento.html')

def hombre(request):
    return render(request,'hombre.html')

def mujer(request):
    producto = Producto.objects.all()

    data = {
        'producto': producto
    }
    return render(request,'mujer.html',data)

def oferta(request):
    return render(request,'oferta.html' )

def formulario(request):
    return render(request,'formulario.html')

#CRUD

@login_required
def agregar_stock(request):

    data = {
        'form': ProductoForm()
    }

    if request.method == 'POST':
        formulario = ProductoForm(data=request.POST, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
        else:
            data["form"] = formulario
    return render(request,'producto/agregar.html',data)

@login_required
def listar(request):
    producto = Producto.objects.all()

    data = {
        'producto': producto
    }

    return render(request,'producto/listar.html',data)

@login_required
def modificar(request, id):

    producto = get_object_or_404(Producto, id=id)

    data = {
        'form' : ProductoForm(instance=producto)
    }

    if request.method == 'POST':
        formulario = ProductoForm(data=request.POST, instance=producto, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request,"Modificado Satisfactoriamente")
            return redirect(to="listar")
        data["form"] = formulario

    return render(request,'producto/modificar.html',data)

@login_required
def eliminar(request, id):

    producto = get_object_or_404(Producto, id=id)
    producto.delete()
    messages.success(request,"Eliminado Satisfactoriamente")
    return redirect(to="listar")

#CARRITO 

def carrito(request):
    return render(request,'carrito.html')

def agregar_producto(request,id):
    carrito = Carrito(request)
    producto = get_object_or_404(Producto, id=id)
    carrito.agregar(producto)
    return redirect("carrito")

def eliminar_producto(request,id):
    carrito = Carrito(request)
    producto = get_object_or_404(Producto, id=id)
    carrito.eliminar(producto)
    return redirect("carrito")

def restar_producto(request, id):
    carrito = Carrito(request)
    producto = get_object_or_404(Producto, id=id)
    carrito.restar(producto)
    return redirect("carrito")

def limpiar_carrito(request):
    carrito = Carrito(request)
    carrito.limpiar()
    return redirect("carrito")

def total_carrito(request):
    carrito = Carrito(request)
    context = {
        "total_carrito": Carrito.total_carrito()
    }
    total = carrito.total_carrito()
    return redirect(request, "carrito.html", context)

thebrickApp/templates/carrito.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>the BRICK | Tienda Oficial</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" >
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel = "icon" href = "https://cdn-icons-png.flaticon.com/512/605/605813.png" type = "image/x-icon">
</head>

<body>

<!----------------Barra Superior------------->


<nav class="navbar sticky-top bg-dark" data-bs-theme="dark" style="padding-top: 5px;">
    <ul class="d-flex flex-grow-1 nav-pills justify-content-end " style="height: 2px; padding-right: 3%;">
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link fw-bold" href="{% url 'logout' %}" style="color:white;">Cerrar Sesión / </a>
      </li>
      <li class="nav-item">
        <a class="nav-link fw-bold" href="#" style="color:white ;">Bienvenido @{{ user.username }}</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link fw-bold" href="{% url 'login' %}" style="color:white;">Ingresar /</a>
      </li>
      <li class="nav-item">
         <a class="nav-link fw-bold" href="{% url 'registro' %}" style="color:white;"> Registrarse</a>
      </li>
      {% endif %}
    </ul>
  </nav>
  
  
  <!----------------NavBar--------------------->
        <nav class="navbar navbar-expand-lg bg-body-tertiary sticky-top">
          <div class="container-fluid">
            <div>
              <a class="nav-link active fw-semibold" aria-current="page" href="{% url 'index' %}">
              <img src="{% static 'Images/logo-thebrick-500x100px.png' %}" alt="Bootstrap" width="30%" height="30%">
              </a>
            </div>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link active fw-semibold" aria-current="page" href="{% url 'lanzamiento' %}">Lanzamientos</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" style="color:black;" href="{% url 'hombre' %}">Hombre</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" style="color:black;" href="{% url 'mujer' %}">Mujer</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link " style="color:black;" href="#">Infantil</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link fw-semibold " style="color:black;" href="{% url 'oferta' %}">Ofertas</a>
                </li>
                {% if perms.app.add_producto %}
                <li class="nav-item">
                  <a class="nav-link" style="color:black;" href="{% url 'listar' %}">Stock</a>
                </li>
                {% endif %}
                {% if perms.app.add_producto %}
                <li class="nav-item">
                  <a class="nav-link" style="color:black;" href="{% url 'agregar_stock' %}">Agregar Producto</a>
                </li>
                {% endif %}
              </ul>
              <a href="{% url 'carrito' %}" class="btn btn-light" role="button" >
                <i class="bi bi-cart"></i>
              </a>
              <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Buscar" aria-label="Search">
                <button class="btn btn-dark" type="submit">
                  <i class="bi bi-search"></i>
                </button>
              </form>
            </div>
          </div>
        </nav>

<!-- Tienda Mujer -->
        <br>
        <br>
        <div class="row">
            <div class="container">
                <table class="table table-bordered">
                <thead>
                    <tr>
                        <th scope="row" colspan="3" class="text-center">Carrito</th>
                    </tr>
                    <tr>
                        <th>Producto</th>
                        <th>Cantidad</th>
                        <th>Precio</th>
                    </tr>
                </thead>
                <tbody>
                {% if request.session.carrito.items %}
                {% for key, value in request.session.carrito.items %}
                    <tr>
                        <td>{{value.nombre}}</td>
                        <td>{{value.precio}}</td>
                        <td>{{value.acumulado}}
                            <a href="{% url 'Add' value.id %}" class="badge btn btn-dark badge-dark">+</a>
                            <a href="{% url 'Sub' value.id %}" class="badge btn btn-dark badge-dark">-</a>
                        </td>
                    </tr>
                {% endfor %}
                {% else %}
                    <tr>
                        <td>
                            <div class="alert alert-danger text-center"> Sin Productos </div>
                        </td>
                    </tr>
                {% endif %}
                    <tr>
                    <th scope="row">Total:</th>
                    <td>$ {{ total_carrito }}</td>
                    </tr>
                </tbody>
                </table>
                <hr>
                <div class="row text-center">
                    <div class="col-6"><a href="{% url 'CLS' %}" class="btn btn-secondary">Limpiar</a></div>
                    <div class="col-6"><a href="#" class="btn btn-dark">Guardar</a></div>
                </div>
            </div>
        </div>

    <!-- Js Bootstrap -->
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    </body>
</html>

thebrickApp/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>the BRICK | Tienda Oficial</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" >
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel = "icon" href = "https://cdn-icons-png.flaticon.com/512/605/605813.png" type = "image/x-icon">
</head>
<body>

<!----------------Barra Superior------------->


<nav class="navbar sticky-top bg-dark" data-bs-theme="dark" style="padding-top: 5px;">
  <ul class="d-flex flex-grow-1 nav-pills justify-content-end " style="height: 2px; padding-right: 3%;">
    {% if user.is_authenticated %}
    <li class="nav-item">
      <a class="nav-link fw-bold" href="{% url 'logout' %}" style="color:white;">Cerrar Sesión / </a>
    </li>
    <li class="nav-item">
      <a class="nav-link fw-bold" href="#" style="color:white ;">Bienvenido @{{ user.username }}</a>
    </li>
    {% else %}
    <li class="nav-item">
      <a class="nav-link fw-bold" href="{% url 'login' %}" style="color:white;">Ingresar /</a>
    </li>
    <li class="nav-item">
       <a class="nav-link fw-bold" href="{% url 'mostrar_registro' %}" style="color:white;"> Registrarse</a>
    </li>
    {% endif %}
  </ul>
</nav>


<!----------------NavBar--------------------->
      <nav class="navbar navbar-expand-lg bg-body-tertiary sticky-top">
        <div class="container-fluid">
          <div>
            <a class="nav-link active fw-semibold" aria-current="page" href="{% url 'index' %}">
            <img src="{% static 'Images/logo-thebrick-500x100px.png' %}" alt="Bootstrap" width="30%" height="30%">
            </a>
          </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active fw-semibold" aria-current="page" href="{% url 'lanzamiento' %}">Lanzamientos</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" style="color:black;" href="{% url 'hombre' %}">Hombre</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" style="color:black;" href="{% url 'mujer' %}">Mujer</a>
              </li>
              <li class="nav-item">
                <a class="nav-link " style="color:black;" href="#">Infantil</a>
              </li>
              <li class="nav-item">
                <a class="nav-link fw-semibold " style="color:black;" href="{% url 'oferta' %}">Ofertas</a>
              </li>
              {% if perms.app.add_producto %}
              <li class="nav-item">
                <a class="nav-link" style="color:black;" href="{% url 'listar' %}">Stock</a>
              </li>
              {% endif %}
              {% if perms.app.add_producto %}
              <li class="nav-item">
                <a class="nav-link" style="color:black;" href="{% url 'agregar_stock' %}">Agregar Stock</a>
              </li>
              {% endif %}
            </ul>
            <a href="{% url 'carrito' %}" class="btn btn-light" role="button" >
              <i class="bi bi-cart"></i>
            </a>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Buscar" aria-label="Search">
              <button class="btn btn-dark" type="submit">
                <i class="bi bi-search"></i>
              </button>
            </form>
          </div>
        </div>
      </nav>
<!--------------------Carousel-------------------------->

  <div id="carousel-LandingPage" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'Images/banner-nike2.jpg' %}" class="img-fluid" alt="nature view" >
      </div>
      <div class="carousel-item">
        <img src="{% static 'Images/banner-converse.jpg' %}" class="img-fluid" alt="nature view">
      </div>
      <div class="carousel-item">
        <img src="{% static 'Images/banner-nike-scaled.jpg' %}" class="img-fluid" alt="nature view">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carousel-LandingPage" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carousel-LandingPage" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

<!-----------------------Banner Ofertas--------------------->

  <div class="container text-center" style="padding-top:3%">
    <div class="row">
      <div class="col-10">
        <!--Imagen-->
        <div>
          <img src="{% static 'Images/imagen-banner.png'%}" class="img-fluid" style="padding-top:3%; padding-bottom: 3%;">
        </div>
      </div>
      <div class="col align-self-center">
        <!--Texto-->
        <h1 class="display-6" style="font-weight: bolder;">Descubre nuestras ofertas</h1>
        <!--Botón-->
          <div>
            <button type="button" class="btn btn-dark" href="#">
                <a href="{% url 'oferta' %}" class="nav-link" style="color:inherit">Comprar</a>
            </button>
          </div>
      </div>
    </div>
  </div>

<!-----------------------Encuesta-------------------------->

<div class="p-3 mb-2 bg-black text-white fw-bolder text-center">
  <p class="fs-3">¡Contesta nuestra encuesta!</p>
  <button type="button" class="btn btn-light">
    <a href="{% url 'formulario' %}" class="nav-link" style="color:inherit">Responder</a>
  </button>
</div>

<!-----------------------Categorías------------------------>

  <div class="container text-center" style="padding-top:3%; padding-bottom:3%">
    <div>
      <h1 class="display-6" style="font-weight: bolder;">Categorías</h1>
    </div>
    <div class="row">
      <div class="col">
        <img src="{% static 'Images/hombre.png'%}" class="img-fluid" alt="nature view" style="padding-top:3%">
        <div style="padding-top:2%">
          <button type="button" class="btn btn-dark" >
            <a href="{% url 'hombre' %}" class="nav-link" style="color:inherit">Hombre</a>
          </button>
        </div>
      </div>
      <div class="col">
        <img src="{% static 'Images/mujer.png'%}" class="img-fluid" alt="nature view" style="padding-top:3%">
        <div style="padding-top:2%">
          <button type="button" class="btn btn-dark">
            <a href="{% url 'mujer' %}" class="nav-link" style="color:inherit">Mujer</a>
          </button>
        </div>
      </div>
      <div class="col">
        <img src="{% static 'Images/infantil.png' %}" class="img-fluid" alt="nature view" style="padding-top:3%">
        <div style="padding-top:2%">
          <button type="button" class="btn btn-dark" href="#">
            <a href="#" class="nav-link" style="color:inherit">Infantil</a>
          </button>
        </div>
      </div>
    </div>
  </div>

<!-----------------------Footer---------------------------->

  <footer class="bg-dark text-white py-4">
    <div class="container">
      <!-- logo -->
      <div class="container-fluid">
        <a href="#" class="col-3 text-reset text-uppercase d-flex align-items-center">
          <img src="{% static 'Images/logo-thebrick-500x100px-blanco.png' %}" height="30%" width="70%">
        </a> 
      </div>
      <br>
      <div class="row">
        <!-- menu -->
        <ul class="col-3 list-unstyled">
          <li class="font-weight-bold text-uppercase">Ayuda</li>
          <li><a href="#" class="nav-link fw-light">Seguimiento de pedido</a></li>
          <li><a href="#" class="nav-link fw-light">Preguntas frecuentes</a></li>
          <li><a href="#" class="nav-link fw-light">Términos y condiciones</a></li>
          <li><a href="#" class="nav-link fw-light">Cambios y devoluciones</a></li>
        </ul>
        <!-- menu2 -->
        <ul class="col-3 list-unstyled">
          <li class="font-weight-bold text-uppercase">Acerca de THE BRICK</li>
          <li><a href="#" class="nav-link fw-light">Empleos</a></li>
          <li><a href="#" class="nav-link fw-light">Inversionistas</a></li>
          <li><a href="#" class="nav-link fw-light">Sustentabilidad</a></li>
          <li><a href="#" class="nav-link fw-light">Nosotros</a></li>
        </ul>
        <!-- redes sociales -->
        <ul class="col-3 list-unstyled">
          <li class="font-weight-bold text-uppercase">Redes Sociales</li>
          <li class="d-flex justify-content-between">
            <!-- Facebook -->
            <a href="https://www.facebook.com" class="text-reset">
              <i class="bi bi-facebook"></i>
            </a>
            <!-- Twitter -->
            <a href="https://www.twitter.com" class="text-reset">
              <i class="bi bi-twitter"></i>
            </a>
            <!-- Instagram -->
            <a href="https://www.instagram.com" class="text-reset">
              <i class="bi bi-instagram"></i>
            </a>
            <!-- Pinterest -->
            <a href="www.pinterest.com" class="text-reset">
              <i class="bi bi-pinterest"></i>
            </a>
          </li>
        </ul>
        </div>
      </div>
    </div>
  </footer>
<!-------------------------------------------------------->

<!-- Js Bootstrap -->
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  </body>
</html>